### PR TITLE
Installation without cython

### PR DESCRIPTION
**Pull request by felipeacsi**
As stated in [cython documentation](http://docs.cython.org/src/reference/compilation.html#distributing-cython-modules) it is recommended to add `c` files to the distribution so the user don't need cython to install the package. This leads to change the `cythonize` method to simply list the `Extension` provide (`_signal` in this case). All of this is reflected in `acoustics/_signal.c` and `setup.py`.

Also, I've wrote a new test method which no requires installation of the package, so you can run the tests before installation with `python setup.py test` and then install.

Finally, I've updated the travis configuration. Now the script launches first the tests and next install the package.

### CODE REVIEW

**Comment by FRidh** [comment]
I am aware it is recommended to distribute the C files. I am fine with generating the C files before packaging, although I don't think it is really worth it. However, I absolutely do not want to include Cython generated C code in git. 

So yes, it is possible to remove cythonize from `ext_modules`, but then a separate command is needed to cythonize the cython code.

However, even when we would do that, it won't solve the real problem, i.e., not being able to import the extension module.

**Comment by felipeacsi** [comment]
> I am aware it is recommended to distribute the C files. I am fine with generating the C files before packaging, although I don't think it is really worth it. However, I absolutely do not want to include Cython generated C code in git.

That explains a lot. Thank you.

> However, even when we would do that, it won't solve the real problem, i.e., not being able to import the extension module.

What do you mean? This is not an issue if you have cython installed with the current master AFAIK.

**Comment by FRidh** [comment]
No, the problem as described in #100 is that a `python setup.py install` cythonizes, compiles, and moves the extension modules (*.so) just fine. However, they (or actually it, since we have only one now) cannot be imported.

**Comment by felipeacsi** [comment]
Actually, you can. Let's try with an example. I will use virtualenvwrapper with python 3.4 to manage the virtual environment (do you use it? If not, I think is similar with other tools). Here is why I execute:

> ~ $ mkvirtualenv i100
> (i100)~ $ pip install -U pip setuptools
> (i100)~ $ pip install numpy ipython cython
> (i100)~ $ pip install numexpr scipy matplotlib pandas==0.14.1
> (i100)~ $ git clone https://github.com/python-acoustics/python-acoustics.git i100
> (i100)~ $ cd i100
> (i100)i100 $ python setup.py install

Then, you can try the package with ipython in the same directory (only to reproduce the error):

> (i100)i100 $ ipython
>  In [1]: import acoustics
> ImportError                               Traceback (most recent call last)
> <ipython-input-1-cdb1bc6650b4> in <module>()
> ----> 1 import acoustics
> 
> /home/felipe/i100/acoustics/__init__.py in <module>()
>      16 import acoustics.standards
>      17 
> ---> 18 from acoustics._signal import Signal

Okay. Now let's try in the root folder.

> In [2]: exit
> (i100)i100 $ cd
> (i100)~ $ ipython
> In [1]: import acoustics
> In [2]: from acoustics._signal import Signal
> In [3]: Signal?
> Type:            type
> String form:     <class 'acoustics._signal.Signal'>
> File:            /home/felipe/.virtualenvs/i100/lib/python3.4/site-packages/acoustics-0.0-py3.4-linux-x86_64.egg/acoustics/_signal.cpython-34m.so
> Init definition: Signal(self, *args, **kwargs)
> Docstring:
> Container for signals.Signal
> 
> `Signal` is a container for acoustics signals.

I hope we can talk better now... This makes sense for you or you catch the error with other setup?

**Comment by FRidh** [comment]
hmm indeed. I just tried again with conda and this latest version, and it does work. OK, I am lost as to why it didn't work before. Maybe somehow somewhere the environment was polluted or...

Anyway, thanks for trying as well!

**Comment by felipeacsi** [comment]
Ok, great!

**Pull request closed without merging**
