### PR TITLE
Revert 20807c7e58f11b55ac15eb6bdec88e7cc6a464ac

### PR DESCRIPTION
**Pull request by FRidh**
Reverts python-acoustics/python-acoustics#199

### CODE REVIEW

**Comment by FRidh** [comment]
Change was already made. Weird that it didn't cause any problems...

**Comment by felipeacsi** [comment]
This seems to partially fix the issue with miniconda 2.4: https://github.com/Geosyntec/wqio/commit/90824fd8432a788585f4cff2708399a525de5162#diff-354f30a63fb0907d4ad57269548329e3
You can see it at https://travis-ci.org/felipeacsi/python-acoustics/builds/90325179. Installations goes well in all cases but tests passed only with python 2.7. It seems to be a problem in python 3.x with:

>  File "setup.py", line 57, in <module>
>    include_dirs=[np.get_include()]

No idea what it might be.

I hope this helps.

**Comment by FRidh** [comment]
@felipeacsi thanks for checking this out! That indeed seems to solve the issue then. The other issue on Python 3.x is I think setuptools related. I've seen this problem occur more often when packaging other Python packages.

**Comment by felipeacsi** [comment]
Good! I pushed the patch.

**Pull request merged**
